### ISSUE TITLE
Bibliografi and working team links

### ISSUE THREAD

**Issue by JoraKasapi** [JoraKasapi/TheAlbanianHouse#11]
Also smth really necessary would be providing a space in the website for a link that provides through a substract the main idea of the project and all the team members specified for the tasks they fulfilled.(giving proper credits to everybody)
A link with all the Bibliography used for the description texts should be  implemented. @sidorelauku

**Comment by sidorelauku** [comment]
We already have a page dedicated to the team and bibliography for the content.
