### ISSUE TITLE
Website development: cleanup of the actual code

### ISSUE THREAD

**Issue by rskikuli** [JoraKasapi/TheAlbanianHouse#6]
Please proceed with the removal of needed materials from the repo, a process that will help us have a productive start for the website. Example of not needed material: https://github.com/JoraKasapi/PreservingAlbania/tree/master/foto_ndertesash

**Comment by sidorelauku** [comment]
I almost removed all not needed files, photos and some content. Now are just a few things to be changed and some images to delete.

**Comment by sidorelauku** [comment]
Closing this as now we have the new content.
