### ISSUE TITLE
Website content license

### ISSUE THREAD

**Issue by rskikuli** [JoraKasapi/TheAlbanianHouse#7]
I propose to use a Creative Commons  Attribution 4.0 International license. This means anyone is free to:

- Share — copy and redistribute the material in any medium or format
- Adapt — remix, transform, and build upon the material for any purpose, even commercially. 

More details about the license can be found here: https://creativecommons.org/licenses/by/4.0/.

Note: this is only about the texts and materials created for this website, NOT materials created by other people such as photos from Wikimedia etc. 

Please confirm this @JoraKasapi .

**Comment by JoraKasapi** [comment]
Yes I confirm the license, Creative Commons Attribution 4.0 International !

**Comment by rskikuli** [comment]
Thanks for the confirmation. Assigning @sidorelauku - please incorporate this in the website.  Once it is done I'll close this.

**Comment by sidorelauku** [comment]
This is word in progress will be finished on the next days.

**Comment by JoraKasapi** [comment]
so did we manage to add the license for the website?

**Comment by sidorelauku** [comment]
This is added CC-BY-SA 4.0 for the content dhe photos from  commons. And AGPL-3.0 for the code.
