### ISSUE TITLE
Website analytics

### ISSUE THREAD

**Issue by rskikuli** [JoraKasapi/TheAlbanianHouse#8]
We need to know the number of visitors that visit the website, but without tracking. Can you make sure we add Matono on the website @kominoshja ?

**Comment by kominoshja** [comment]
Sure. Just waiting on the domain name

**Comment by JoraKasapi** [comment]
@kominoshja Boris can we check on how to do this now?

**Comment by kominoshja** [comment]
Sent @sidorelauku the instructions

**Comment by sidorelauku** [comment]
@JoraKasapi this is done. Closing the issue.
